import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import { ArrowLeft, Scale, X } from "lucide-react";
import LoadingSpinner from "../components/LoadingSpinner";

const storageKey = "propertyComparison";
export default function CompareProperties() {
  const [properties, setProperties] = useState(null);
  const remove = (id) => { const ids = JSON.parse(localStorage.getItem(storageKey) || "[]").filter((item) => item !== id); localStorage.setItem(storageKey, JSON.stringify(ids)); setProperties((items) => items.filter((item) => item._id !== id)); };
  useEffect(() => { axios.get(`${import.meta.env.VITE_API_URL}/api/listings`).then(({ data }) => { const ids = JSON.parse(localStorage.getItem(storageKey) || "[]"); setProperties(ids.map((id) => data.find((item) => item._id === id)).filter(Boolean)); }).catch(() => setProperties([])); }, []);
  if (!properties) return <LoadingSpinner fullScreen message="Preparing your comparison…"/>;
  if (!properties.length) return <main className="flex min-h-[70vh] items-center justify-center px-5" style={{ background: "var(--canvas)" }}><div className="text-center"><Scale className="mx-auto text-emerald-800" size={36}/><h1 className="display-face mt-5 text-5xl font-bold">Nothing to compare yet.</h1><p className="mt-4 text-stone-500">Add up to three properties from their details pages.</p><Link to="/listings" className="luxury-button mt-7 inline-flex rounded-xl px-5 py-3 font-bold">Explore properties</Link></div></main>;
  const rows = [{ label: "Price", value: (item) => `₹${Number(item.price).toLocaleString()}` }, { label: "Location", value: (item) => item.location }, { label: "Property type", value: (item) => item.propertyType }, { label: "Size", value: (item) => item.size }, { label: "Status", value: (item) => item.status }, { label: "Amenities", value: (item) => item.amenities?.join(", ") || "—" }];
  return <main className="min-h-screen px-5 py-16" style={{ background: "var(--canvas)" }}><div className="mx-auto max-w-[76rem]"><Link to="/listings" className="inline-flex items-center gap-2 text-sm font-bold text-stone-500"><ArrowLeft size={16}/> Back to listings</Link><div className="mt-10"><p className="editorial-label text-amber-700">Your shortlist</p><h1 className="display-face mt-3 text-6xl font-bold">Compare properties.</h1><p className="mt-4 text-stone-500">Review the defining details side by side before arranging a visit.</p></div><div className="mt-10 overflow-x-auto"><div className="min-w-[720px] overflow-hidden rounded-[1.5rem] border border-stone-200 bg-white dark:border-slate-700 dark:bg-slate-900"><div className="grid grid-cols-[180px_repeat(3,minmax(220px,1fr))] border-b border-stone-200 dark:border-slate-700"><div className="p-5 text-xs font-black uppercase tracking-widest text-stone-400">Property</div>{properties.map((item) => <div key={item._id} className="relative border-l border-stone-200 p-5 dark:border-slate-700"><button onClick={() => remove(item._id)} aria-label={`Remove ${item.title}`} className="absolute right-3 top-3 rounded-full bg-white/90 p-1 text-stone-500 shadow"><X size={15}/></button><img src={item.images?.[0]} alt="" className="h-32 w-full rounded-xl object-cover"/><Link to={`/property/${item._id}`} className="mt-3 block font-black hover:text-emerald-800 dark:text-white">{item.title}</Link></div>)}</div>{rows.map((row) => <div key={row.label} className="grid grid-cols-[180px_repeat(3,minmax(220px,1fr))] border-b border-stone-200 last:border-0 dark:border-slate-700"><div className="bg-stone-50 p-5 text-sm font-bold text-stone-500 dark:bg-slate-800">{row.label}</div>{properties.map((item) => <div key={item._id} className="border-l border-stone-200 p-5 text-sm leading-6 text-stone-700 dark:border-slate-700 dark:text-stone-300">{row.value(item)}</div>)}</div>)}</div></div></div></main>;
}
