import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { ArrowLeft, KeyRound, Mail, ShieldCheck } from "lucide-react";
import { toast } from "react-hot-toast";

const api = `${import.meta.env.VITE_API_URL}/api/auth`;

export default function ForgotPassword() {
  const [email, setEmail] = useState(""); const [otp, setOtp] = useState(""); const [step, setStep] = useState("email"); const [loading, setLoading] = useState(false); const [secondsUntilResend, setSecondsUntilResend] = useState(0); const navigate = useNavigate();
  useEffect(() => { if (!secondsUntilResend) return; const timer = window.setTimeout(() => setSecondsUntilResend((seconds) => seconds - 1), 1000); return () => window.clearTimeout(timer); }, [secondsUntilResend]);
  const requestCode = async (event) => { event?.preventDefault(); setLoading(true); try { const { data } = await axios.post(`${api}/forgot-password`, { email }); toast.success(data.message); setStep("otp"); setSecondsUntilResend(60); } catch (error) { toast.error(error.response?.data?.error || "Unable to send a verification code."); } finally { setLoading(false); } };
  const verifyCode = async (event) => { event.preventDefault(); setLoading(true); try { const { data } = await axios.post(`${api}/verify-reset-otp`, { email, otp }); sessionStorage.setItem("passwordResetToken", data.resetToken); navigate("/reset-password"); } catch (error) { toast.error(error.response?.data?.error || "Unable to verify the code."); } finally { setLoading(false); } };
  return <main className="min-h-screen px-5 py-20" style={{ background: "var(--canvas)" }}><div className="luxury-surface mx-auto max-w-lg rounded-[2rem] p-8 md:p-12"><Link to="/login" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-stone-500 hover:text-emerald-900 dark:hover:text-emerald-200"><ArrowLeft size={16}/> Back to login</Link><div className="mb-10"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-950 text-[#e7c47e]">{step === "email" ? <Mail size={21}/> : <KeyRound size={21}/>}</div><p className="editorial-label text-amber-700">Secure recovery</p><h1 className="display-face mt-3 text-5xl font-bold">{step === "email" ? "Reset your access." : "Enter your code."}</h1><p className="mt-4 leading-7 text-stone-600 dark:text-stone-400">{step === "email" ? "Enter the email address registered with your Estatera account. We’ll send a one-time verification code." : `We sent a six-digit code to ${email}. It expires in 10 minutes.`}</p></div>{step === "email" ? <form onSubmit={requestCode} className="space-y-5"><label className="block"><span className="editorial-label text-stone-500">Registered email</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 p-4 outline-none ring-emerald-800/20 focus:ring-2 dark:border-stone-700 dark:bg-slate-800" placeholder="you@example.com"/></label><button disabled={loading} className="luxury-button w-full rounded-xl py-4 font-bold disabled:opacity-60">{loading ? "Sending code…" : "Send verification code"}</button></form> : <form onSubmit={verifyCode} className="space-y-5"><label className="block"><span className="editorial-label text-stone-500">One-time code</span><input required inputMode="numeric" maxLength="6" value={otp} onChange={(event) => setOtp(event.target.value.replace(/\D/g, ""))} className="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 p-4 text-center text-2xl font-bold tracking-[.45em] outline-none ring-emerald-800/20 focus:ring-2 dark:border-stone-700 dark:bg-slate-800" placeholder="000000"/></label><button disabled={loading || otp.length !== 6} className="luxury-button w-full rounded-xl py-4 font-bold disabled:opacity-60">{loading ? "Verifying…" : "Verify code"}</button><button type="button" disabled={loading || secondsUntilResend > 0} onClick={requestCode} className="w-full text-sm font-bold text-emerald-800 disabled:text-stone-400 dark:text-emerald-300">{secondsUntilResend ? `Resend code in ${secondsUntilResend}s` : "Resend verification code"}</button><button type="button" onClick={() => { setStep("email"); setOtp(""); }} className="w-full text-sm font-bold text-stone-500">Use another email</button></form>}</div></main>;
}
