import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, MapPin, Search, ShieldCheck, Sparkles } from "lucide-react";
import PropertyCard from "../components/PropertyCard";
import PropertyCardSkeleton from "../components/common/PropertyCardSkeleton";
import Testimonials from "../components/Testimonials";
import { getProperties } from "../services/property.service";

export default function Home() {
  const navigate = useNavigate();
  const [properties, setProperties] = useState([]); const [location, setLocation] = useState(""); const [type, setType] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { getProperties().then(({ data }) => setProperties(data.slice(0, 3))).catch(console.error).finally(() => setLoading(false)); }, []);
  const search = () => { const query = new URLSearchParams(); if (location.trim()) query.set("location", location.trim()); if (type) query.set("type", type); navigate(`/listings?${query}`); };
  return <div className="overflow-hidden" style={{ background: "var(--canvas)" }}>
    <section className="relative min-h-[760px] overflow-hidden bg-[#10241d] px-5 pb-24 pt-20 text-white md:px-10"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=85" alt="Contemporary residence" className="absolute inset-0 h-full w-full object-cover opacity-60"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,26,20,.96)_0%,rgba(9,26,20,.72)_48%,rgba(9,26,20,.24)_100%)]"/><div className="relative mx-auto grid max-w-[76rem] items-end gap-12 pt-24 lg:grid-cols-[1.1fr_.9fr]"><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><p className="editorial-label mb-6 flex items-center gap-2 text-[#e7c47e]"><Sparkles size={14}/> Curated residences · Tamil Nadu</p><h1 className="display-face max-w-3xl text-6xl leading-[.92] md:text-8xl">A more considered way to find <i>home.</i></h1><p className="mt-8 max-w-xl text-lg leading-8 text-stone-200">Explore a private collection of verified land, homes, and apartments selected for their place, potential, and enduring character.</p></motion.div><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, delay: .15 }} className="rounded-[1.6rem] border border-white/20 bg-white/10 p-5 backdrop-blur-xl md:p-6"><p className="editorial-label mb-5 text-stone-200">Begin your search</p><div className="space-y-3"><label className="flex items-center gap-3 rounded-xl bg-white px-4 text-slate-800"><MapPin size={18} className="text-emerald-800"/><input value={location} onChange={(e) => setLocation(e.target.value)} onKeyDown={(e) => e.key === "Enter" && search()} className="w-full bg-transparent py-4 outline-none" placeholder="City, locality, or landmark"/></label><div className="grid grid-cols-[1fr_auto] gap-3"><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-xl bg-white px-4 py-4 text-slate-800 outline-none"><option value="">All property types</option><option value="Land">Land</option><option value="House">House</option><option value="Apartment">Apartment</option></select><button onClick={search} className="luxury-button flex items-center gap-2 rounded-xl px-6 font-bold"><Search size={18}/><span className="hidden sm:inline">Explore</span></button></div></div></motion.div></div></section>
    <section className="border-b border-stone-300 bg-[#f0ede4] py-6 dark:border-stone-700 dark:bg-[#16231e]"><div className="mx-auto flex max-w-[76rem] flex-wrap justify-between gap-5 px-5 text-sm font-semibold text-stone-600 dark:text-stone-300"><span>INDEPENDENTLY VERIFIED</span><span>•</span><span>LOCAL EXPERTISE</span><span>•</span><span>PRIVATE VIEWINGS</span><span>•</span><span>END-TO-END GUIDANCE</span></div></section>
    <section className="mx-auto max-w-[76rem] px-5 py-24 md:px-10"><div className="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p className="editorial-label mb-3 text-amber-700">The collection</p><h2 className="display-face text-5xl text-stone-900 dark:text-stone-100">Spaces with a point of view.</h2></div><Link to="/listings" className="flex items-center gap-2 border-b border-emerald-900 pb-1 text-sm font-bold text-emerald-950 dark:text-emerald-200">View every property <ArrowRight size={16}/></Link></div><div className="grid gap-7 md:grid-cols-3">{loading ? [1,2,3].map((key) => <PropertyCardSkeleton key={key}/>) : properties.length ? properties.map((p) => <PropertyCard key={p._id} property={p}/>) : <div className="col-span-full rounded-3xl border border-dashed border-stone-300 p-12 text-center text-stone-500">Our next collection is being prepared. Please return soon.</div>}</div></section>
    <section className="mx-auto grid max-w-[76rem] gap-10 px-5 pb-24 md:grid-cols-2 md:px-10"><div className="rounded-[2rem] bg-[#d9e2d9] p-9 dark:bg-[#20342a]"><ShieldCheck className="mb-10 text-emerald-900 dark:text-emerald-300" size={30}/><p className="editorial-label text-emerald-800 dark:text-emerald-300">Confidence, built in</p><h2 className="display-face mt-3 text-4xl">Every opportunity begins with clarity.</h2><p className="mt-5 max-w-md leading-7 text-stone-600 dark:text-stone-300">From first search to final visit, our team makes the details legible and the next step simple.</p><Link to="/contact" className="mt-8 inline-flex items-center gap-2 font-bold text-emerald-900 dark:text-emerald-200">Speak with an advisor <ArrowRight size={16}/></Link></div><div className="relative min-h-[340px] overflow-hidden rounded-[2rem]"><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85" alt="Modern interior" className="h-full w-full object-cover"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 p-8 text-white"><p className="editorial-label text-[#e7c47e]">A private introduction</p><p className="display-face mt-2 text-3xl">The right address changes everything.</p></div></div></section><Testimonials/>
  </div>;
}
