import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { toast } from "react-hot-toast";
export default function ResetPassword() {
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); if (password !== confirmPassword) return toast.error("Passwords do not match."); setLoading(true); try { const resetToken = sessionStorage.getItem("passwordResetToken"); if (!resetToken) throw new Error("No reset session"); const { data } = await axios.post(`${import.meta.env.VITE_API_URL}/api/auth/reset-password`, { resetToken, password, confirmPassword }); sessionStorage.removeItem("passwordResetToken"); toast.success(data.message); navigate("/login"); } catch (error) { toast.error(error.response?.data?.error || "Your reset session is invalid or expired."); } finally { setLoading(false); } };
  return <main className="min-h-screen px-5 py-20" style={{ background: "var(--canvas)" }}><div className="luxury-surface mx-auto max-w-lg rounded-[2rem] p-8 md:p-12"><Link to="/forgot-password" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-stone-500 hover:text-emerald-900 dark:hover:text-emerald-200"><ArrowLeft size={16}/> Start over</Link><div className="mb-10"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-950 text-[#e7c47e]"><LockKeyhole size={21}/></div><p className="editorial-label text-amber-700">Verified recovery</p><h1 className="display-face mt-3 text-5xl font-bold">Set a new password.</h1><p className="mt-4 leading-7 text-stone-600 dark:text-stone-400">Use at least eight characters with uppercase, lowercase, and a number.</p></div><form onSubmit={submit} className="space-y-5"><Field label="New password" value={password} onChange={setPassword}/><Field label="Confirm password" value={confirmPassword} onChange={setConfirmPassword}/><button disabled={loading} className="luxury-button w-full rounded-xl py-4 font-bold disabled:opacity-60">{loading ? "Resetting password…" : "Reset password"}</button></form></div></main>;
}
function Field({ label, value, onChange }) { return <label className="block"><span className="editorial-label text-stone-500">{label}</span><input required type="password" value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-stone-200 bg-stone-50 p-4 outline-none ring-emerald-800/20 focus:ring-2 dark:border-stone-700 dark:bg-slate-800"/></label>; }
